create table if not exists public.usuarios (
    id_usuario bigint generated by default as identity primary key,
    nome text not null,
    cpf text unique,
    telefone text not null unique,
    senha text not null,
    tipo_perfil text not null check (tipo_perfil in ('necessitado', 'voluntario')),
    latitude double precision,
    longitude double precision
);

alter table public.usuarios add column if not exists cpf text;
create unique index if not exists usuarios_cpf_idx on public.usuarios(cpf) where cpf is not null;

create table if not exists public.pedidos (
    id_pedido bigint generated by default as identity primary key,
    id_solicitante bigint references public.usuarios(id_usuario),
    id_voluntario bigint references public.usuarios(id_usuario),
    categoria text not null,
    descricao_outros text,
    valor_proposto numeric(10, 2) check (valor_proposto > 0),
    valor_acordado numeric(10, 2) check (valor_acordado > 0),
    latitude double precision,
    longitude double precision,
    status text not null default 'pendente'
        check (status in ('pendente', 'aceito', 'em_andamento', 'concluido', 'cancelado'))
);

alter table public.pedidos add column if not exists valor_proposto numeric(10, 2);
alter table public.pedidos add column if not exists valor_acordado numeric(10, 2);

create table if not exists public.propostas (
    id_proposta bigint generated by default as identity primary key,
    id_pedido bigint not null references public.pedidos(id_pedido),
    id_usuario bigint not null references public.usuarios(id_usuario),
    valor numeric(10, 2) not null check (valor > 0),
    status text not null default 'pendente'
        check (status in ('pendente', 'aceita', 'recusada')),
    criado_em timestamptz not null default now()
);

create index if not exists propostas_pedido_idx on public.propostas(id_pedido, id_proposta);

create table if not exists public.mensagens (
    id_mensagem bigint generated by default as identity primary key,
    id_pedido bigint not null references public.pedidos(id_pedido),
    id_remetente bigint not null references public.usuarios(id_usuario),
    texto text not null,
    criado_em timestamptz not null default now()
);

create index if not exists pedidos_status_idx on public.pedidos(status);
create index if not exists pedidos_solicitante_idx on public.pedidos(id_solicitante);
create index if not exists pedidos_voluntario_idx on public.pedidos(id_voluntario);
create index if not exists mensagens_pedido_idx on public.mensagens(id_pedido, id_mensagem);
