create table if not exists public.usuarios (
    id_usuario bigint generated by default as identity primary key,
    nome text not null,
    telefone text not null unique,
    senha text not null,
    tipo_perfil text not null check (tipo_perfil in ('necessitado', 'voluntario')),
    latitude double precision,
    longitude double precision
);

create table if not exists public.pedidos (
    id_pedido bigint generated by default as identity primary key,
    id_solicitante bigint references public.usuarios(id_usuario),
    id_voluntario bigint references public.usuarios(id_usuario),
    categoria text not null,
    descricao_outros text,
    latitude double precision,
    longitude double precision,
    status text not null default 'pendente'
        check (status in ('pendente', 'aceito', 'em_andamento', 'concluido', 'cancelado'))
);

create table if not exists public.mensagens (
    id_mensagem bigint generated by default as identity primary key,
    id_pedido bigint not null references public.pedidos(id_pedido),
    id_remetente bigint not null references public.usuarios(id_usuario),
    texto text not null,
    criado_em timestamptz not null default now()
);

create index if not exists pedidos_status_idx on public.pedidos(status);
create index if not exists pedidos_solicitante_idx on public.pedidos(id_solicitante);
create index if not exists pedidos_voluntario_idx on public.pedidos(id_voluntario);
create index if not exists mensagens_pedido_idx on public.mensagens(id_pedido, id_mensagem);
